### ISSUE TITLE
Glass Type | support in json (zohar) and newCocktail (einav)

### ISSUE THREAD

**Issue by shahafhermann** [zoharhen/Cocktails#13]
Property added to Cocktail data class.
I'm currently getting new models for the glasses, will be up by tomorrow.
We need to add the corresponding glasses to the default json, as well as a glass option for the "new cocktail" screen (dropdown maybe?)

~ Shahaf

**Comment by zoharhen** [comment]
@shahafhermann @enavhasson Amnon asked to try to avoid drop downs, unless there are no more then ~3 options to choose.  maybe chip can be a better solution, similar to the 'filter' view i started to implement. WDYT? 
see single-line chip collection for example: https://images.app.goo.gl/8mBeKsVuRNUw5Rgu9

**Comment by shahafhermann** [comment]
Sounds like a dumb principal, but we're here for the points. So yeah, chip would be alright for this purpose. We'll probably have 4-5 different options.

**Comment by enavhasson** [comment]
so I think we need to decided now which info from the website ( cocktails data)  we want to support .
and now work twice on the same think , or change it in the future

**Comment by shahafhermann** [comment]
Glass type is inserted by us manually, no need to find it online.

**Comment by enavhasson** [comment]
https://material.io/components/buttons#contained-button
I found this website . I recommend to take a look , they have examples of what "Do" and "Don't"

**Comment by shahafhermann** [comment]
Added to json.

**Comment by shahafhermann** [comment]
Done.
