### ISSUE TITLE
units for measuring

### ISSUE THREAD

**Issue by enavhasson** [zoharhen/Cocktails#14]
Supports multiple units for measuring different liquid weight and volume mas.

**Comment by shahafhermann** [comment]
In my opinion: Ounces are the standard measuring unit so we should just stick with it. I've never seen any recipe with any different unit.

We should just make sure the the unit is displayed, and that the user has some UI feedback by adding "oz." after every such field. You could probably close the issue....

**Comment by zoharhen** [comment]
cool, closing this issue then
