### ISSUE TITLE
add splash screen

### ISSUE THREAD

**Issue by zoharHenMicrosoft** [zoharhen/Cocktails#4]

**Comment by zoharhen** [comment]
@enavhasson @shahafhermann not sure it's really needed, WDYT?

**Comment by enavhasson** [comment]
I think yes ,because it takes a few seconds for the icons to load in the main screen.

**Comment by zoharhen** [comment]
that's it, that we are not going to save it to the cache in the meanwhile anyway, as we don't have enough space for it - so it might be redundant. am i wrong? anyway, would you like to be the owner of this task? I want to finish with my current tasks and done with this project :)
