### ISSUE TITLE
Scrolling activity | fix grid width

### ISSUE THREAD

**Issue by zoharHenMicrosoft** [zoharhen/Cocktails#44]
on me

**Comment by enavhasson** [comment]
The problem has not been fixed , and now its cut the items.
![Screenshot_20200920-131059_Cocktails](https://user-images.githubusercontent.com/57680245/93709099-414af200-fb44-11ea-9e69-d8421f765a9a.jpg)

**Comment by zoharhen** [comment]
@enavhasson oh nooooooooooooooooooooooooooooooooooooooooooooooooo, not again! thanks for letting me know!
BTW - where is the search icon here? and what is this weird gray rectangle to the left? :O

**Comment by enavhasson** [comment]
the weird gray rectangle to the left, is widget in my phone . and the search icon not appear in the last version.
in your phone it's appear?

**Comment by zoharhen** [comment]
yes, of course. which phone are you using? did you make any changes in the current branch? this is so weird, all works fine with 2 phones that i have checked :O

**Comment by enavhasson** [comment]
ok. only in my phone is not appear . in the emulator I see the icon . maybe is affected by the way you init this buttons ,and the width .
my phone is galaxy S8

**Comment by zoharhen** [comment]
shouldn't be related.. @shahafhermann what do you see? same issues as in Enav phone? :O

**Comment by zoharhen** [comment]
reproduced only with screen-zoom feature, close.
