### ISSUE TITLE
fix keyboard focus (hide keyboard when not needed)

### ISSUE THREAD

**Issue by zoharhen** [zoharhen/Cocktails#60]
search bar - done
contact us - @shahafhermann 
create new cocktail (all text fields) - @enavhasson

**Comment by shahafhermann** [comment]
I'm pretty sure I handled it already. Was this issue spotted anywhere in the contact us pane?

**Comment by zoharhen** [comment]
Yes

**Comment by shahafhermann** [comment]
Done in 'contact us'.

**Comment by enavhasson** [comment]
DONE -in create new cocktail (all text fields)
